
--**************************************
-- Derive Event Type Dimension Table
--**************************************

CREATE TABLE dim_event_type (
	type_name text NULL,
	type_id int2 NOT NULL GENERATED BY DEFAULT AS identity
);

insert into dim_event_type(type_name) select distinct event_type from songkick_uk_events;

ALTER TABLE dim_event_type ADD CONSTRAINT dim_event_type_pk PRIMARY KEY (type_id);

--**************************************
-- Derive DayOfWeek Dimension Table
--**************************************
create table dim_dayofweek as
SELECT distinct to_char(start_date, 'd') as day_id, to_char(start_date, 'Day') as dayofweek
FROM songkick_uk_events sue 
order by 1;

ALTER TABLE dim_dayofweek ADD CONSTRAINT dim_dayofweek_pk PRIMARY KEY (day_id);


create table fct_ukevents as
select a.time_id, b.type_id, d.day_id, count(c.event_id) as no_of_events 
from dim_time a, dim_event_type b, songkick_uk_events c, dim_dayofweek d
where c.country = 'UK' and c.event_type = b.type_name
and a.time_id = to_char(c.start_date, 'yyyy') || to_char(c.start_date, 'mm') || to_char(c.start_date, 'iw')
and d.day_id = to_char(c.start_date, 'd')
group by a.time_id, b.type_id, d.day_id
order by type_id, time_id asc, d.day_id asc;

ALTER TABLE fct_ukevents ADD CONSTRAINT fct_ukevents_pk PRIMARY KEY (time_id,type_id,day_id);


select * from fct_ukevents;