--**************************************
-- Derive Event Type Dimension Table
--**************************************
drop table if exists dim_event_type cascade;

CREATE TABLE dim_event_type (
	type_name text NULL,
	type_id int2 NOT NULL GENERATED BY DEFAULT AS identity
);

insert into dim_event_type(type_name) select distinct event_type from songkick_uk_events;

ALTER TABLE dim_event_type ADD CONSTRAINT dim_event_type_pk PRIMARY KEY (type_id);

--**************************************
-- Derive DayOfWeek Dimension Table
--**************************************
drop table if exists dim_dayofweek cascade;

create table dim_dayofweek as
SELECT distinct to_char(start_date, 'd') as day_id, to_char(start_date, 'Day') as dayofweek
FROM songkick_uk_events sue 
order by 1;

ALTER TABLE dim_dayofweek ADD CONSTRAINT dim_dayofweek_pk PRIMARY KEY (day_id);


--******************************************
--	Create dim_artist_group table
--******************************************
drop table if exists dim_artist_group cascade;
CREATE TABLE dim_artist_group (
	group_id smallint NULL GENERATED BY DEFAULT AS IDENTITY,
	group_name varchar NULL
);
ALTER TABLE dim_artist_group ADD CONSTRAINT dim_artist_group_pk PRIMARY KEY (group_id);


insert into dim_artist_group(group_name) values ('Spotify Artist');
insert into dim_artist_group(group_name) values ('Others');



--******************************************
--	Create dim_event_artist table
--******************************************
drop table if exists dim_event_artist cascade;

create table dim_event_artist as 
select distinct mbid from songkick_uk_events sue; 

ALTER TABLE dim_event_artist ADD CONSTRAINT dim_event_artist_pk PRIMARY KEY (mbid);
ALTER TABLE dim_event_artist ADD group_id smallint NULL;

update dim_event_artist a
set group_id = (select group_id from dim_artist_group b where group_name = 'Spotify Artist')
where a.mbid in (select c.artist_mbid from dim_spotifyartist c);

update dim_event_artist a
set group_id = (select group_id from dim_artist_group b where group_name = 'Others')
where a.mbid not in (select c.artist_mbid from dim_spotifyartist c);

ALTER TABLE dim_event_artist ADD CONSTRAINT dim_event_artist_fk FOREIGN KEY (group_id) REFERENCES dim_artist_group(group_id);




drop table if exists fct_ukevents cascade; 

create table fct_ukevents as
select a.time_id, b.type_id, d.day_id, f.mbid,c.country, count(c.event_id) as no_of_events 
from dim_time a, dim_event_type b, songkick_uk_events c, dim_dayofweek d, dim_event_artist f, dim_artist_group g
where c.country = 'UK' 
and c.event_type = b.type_name
and a.time_id = to_char(c.start_date, 'yyyy') || to_char(c.start_date, 'mm') --|| to_char(c.start_date, 'iw')
and d.day_id = to_char(c.start_date, 'd') --and c.start_date  = '2019-06-01'
and f.mbid = c.mbid --and c.mbid = '854b0687-f9fc-4109-b59f-dbe84ebc5de6'
group by a.time_id, b.type_id, d.day_id, f.mbid,c.country
order by no_of_events desc, type_id, time_id asc, d.day_id asc;

ALTER TABLE fct_ukevents ADD CONSTRAINT fct_ukevents_pk PRIMARY KEY (time_id,day_id,type_id, mbid, country);

ALTER TABLE public.fct_ukevents ADD CONSTRAINT fct_ukevents_fk FOREIGN KEY (day_id) REFERENCES public.dim_dayofweek(day_id);
ALTER TABLE public.fct_ukevents ADD CONSTRAINT fct_ukevents_fk_1 FOREIGN KEY (mbid) REFERENCES public.dim_event_artist(mbid);
ALTER TABLE public.fct_ukevents ADD CONSTRAINT fct_ukevents_fk_2 FOREIGN KEY (type_id) REFERENCES public.dim_event_type(type_id);
ALTER TABLE public.fct_ukevents ADD CONSTRAINT fct_ukevents_fk_3 FOREIGN KEY (time_id) REFERENCES public.dim_time(time_id);



/*
--select * from fct_ukevents;

--Adding start_time dimension to the star schema
drop table if exists fct_ukevents_start_time cascade; 

create table fct_ukevents_start_time as
select a.time_id, b.type_id, d.day_id, e.start_time_id, f.mbid, c.country,  count(c.event_id) as no_of_events 
from dim_time a, dim_event_type b, songkick_uk_events c, dim_dayofweek d, dim_event_start_time e, dim_event_artist f
where c.country = 'UK' and c.event_type = b.type_name
and a.time_id = to_char(c.start_date, 'yyyy') || to_char(c.start_date, 'mm') --|| to_char(c.start_date, 'iw')
and d.day_id = to_char(c.start_date, 'd')
and e.start_time_id = to_char(c.start_time, 'HH24MI') or c.start_time is null
and f.mbid = c.mbid
group by a.time_id, b.type_id, d.day_id, e.start_time_id, f.mbid, c.country
order by type_id, time_id asc, d.day_id asc, e.start_time_id asc;

ALTER TABLE fct_ukevents_start_time ADD CONSTRAINT fct_ukevents_start_time_pk PRIMARY KEY (time_id,type_id,day_id,start_time_id, mbid);

--select * from fct_ukevents_start_time

select count(1) from songkick_uk_events sue 

update songkick_uk_events 
set start_time = null
where to_char(start_time, 'HH24MI') = '1111'

select * from songkick_uk_events sue where start_time is null
*/
