/*
update songkick_uk_events 
set event_name = 'The Alarm with Morriston Orpheus Choir Dave Sharp and Chris Summerill at Solus Cardiff University Students'' Union (June 29 2019'
where event_id = 34996004;
*/

ALTER TABLE public.songkick_uk_venues ALTER COLUMN venue_id TYPE float8 USING venue_id::float8;


drop table if exists dim_cities cascade;
CREATE TABLE dim_cities (
	city_id smallint NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar not NULL
);
ALTER TABLE dim_cities ADD CONSTRAINT dim_cities_pk PRIMARY KEY (city_id);

insert into dim_cities (name)
select distinct city from songkick_uk_venues;


drop table if exists dim_venues cascade;
create table dim_venues as 
select a.venue_id, a."name", a.post_code, a.street, a.country, a.capacity, b.city_id 
from songkick_uk_venues a, dim_cities b
where a.city = b."name";

ALTER TABLE dim_venues ADD CONSTRAINT dim_venues_pk PRIMARY KEY (venue_id);
ALTER TABLE dim_venues ADD CONSTRAINT dim_venues_fk FOREIGN KEY (city_id) REFERENCES public.dim_cities(city_id);


update songkick_uk_events 
set popularity = (select avg(popularity) from songkick_uk_events de2 where de2.event_id = 32538374)
where event_id in (32538374);

update songkick_uk_events 
set popularity = (select avg(popularity) from songkick_uk_events de2 where de2.event_id = 39050644)
where event_id in (39050644);


update songkick_uk_events 
set popularity = (select avg(popularity) from songkick_uk_events de2 where de2.event_id = 35186709)
where event_id in (35186709);

update songkick_uk_events 
set popularity = (select avg(popularity) from songkick_uk_events de2 where de2.event_id = 36819199)
where event_id in (36819199);

update songkick_uk_events 
set popularity = (select avg(popularity) from songkick_uk_events de2 where de2.event_id = 36894999)
where event_id in (36894999);

update songkick_uk_events 
set popularity = (select avg(popularity) from songkick_uk_events de2 where de2.event_id = 38038984)
where event_id in (38038984);

/*
drop table if exists dim_events cascade;
create table dim_events as 
select distinct event_id, event_name, venue_id, start_date, start_time, country, popularity 
from songkick_uk_events sue;
ALTER TABLE public.dim_events ADD CONSTRAINT dim_events_pk PRIMARY KEY (event_id);
*/
drop table if exists fct_event_venues cascade;

create table fct_event_venues as
select d.time_id, b.venue_id, e.mbid, count(a.event_id) no_of_event, avg(a.popularity) avg_popularity
from songkick_uk_events a, dim_venues b, dim_time d, dim_event_artist e
where 
a.venue_id = b.venue_id 
and a.mbid = e.mbid
and d.time_id = to_char(a.start_date, 'yyyy') || to_char(a.start_date, 'mm')
group by d.time_id, b.venue_id, e.mbid;

ALTER TABLE fct_event_venues ADD CONSTRAINT fct_event_city_pk PRIMARY KEY (time_id,venue_id,mbid);

ALTER TABLE fct_event_venues ADD CONSTRAINT fct_event_venues_fk FOREIGN KEY (mbid) REFERENCES dim_event_artist(mbid);
ALTER TABLE fct_event_venues ADD CONSTRAINT fct_event_city_fk_1 FOREIGN KEY (time_id) REFERENCES public.dim_time(time_id);
ALTER TABLE fct_event_venues ADD CONSTRAINT fct_event_city_fk_2 FOREIGN KEY (venue_id) REFERENCES public.dim_venues(venue_id);





/*
select venue_id, sum(no_of_event) from fct_event_venues
--where venue_id = 4233369
group by venue_id
order by 2 desc;
*/


/*
--Events with venue id but no venue details:
event_id	Venue_id
38949857	3000119
36898559	3890299
37950739	3463554
38772909	2597493
38140654	4233369
38258009	4272494
37807219	4233369
39182420	755696
37545514	4233369
39585878	4386949
*/

